image: Visual Studio 2017

install:
  # Node on appveyor is too old
  - cinst nodejs --version  9.2.0

matrix:
  fast_finish: true

cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - subnautica-map\node_modules                    # local npm modules
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3
  - "%LOCALAPPDATA%\\Yarn"

build_script:
  - nuget restore
  - msbuild /m /p:Configuration=Release /p:PublicRelease=true /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /clp:v=n /bl /t:package subnautica-watcher.proj

artifacts:
- path: msbuild.binlog
  name: MSBuild Log
- path: 'subnautica-watcher-release-*.zip'
  name: Release Zip

on_failure:
- appveyor PushArtifact msbuild.binlog

deploy:
  release: v$(appveyor_build_version)
  description: 'Automated Release'
  provider: GitHub
  auth_token:
    secure: HyTlpe7AdOity1wfUhQuIhrFID/E2CtxE/TZfwQYU0D4lFuDfgXgWDGSvgU/7jQN # your encrypted token from GitHub
  artifact: 'subnautica-watcher-release-*.zip' # upload all packages to release assets
  draft: false
  prerelease: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
