image: Visual Studio 2017

matrix:
  fast_finish: true

cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - node_modules                    # local npm modules
  - '%LocalAppData%\NuGet\v3-cache' # NuGet v3

install:
  - cup chocolatey
  - cinst yarn

build_script:
  - ps: ./build.ps1 /m /p:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
- path: msbuild.binlog
  name: MSBuild Log
- path: 'bin\**\msbuild-structured-log-viewer*.nupkg'
  name: Chocolatey Package

on_failure:
- appveyor PushArtifact msbuild.binlog